name: oxidized
description: A library of Rust-like types, including Option and Result.
version: 1.0.0
homepage: https://github.com/nlfiedler/oxidized
repository: https://github.com/nlfiedler/oxidized.git
issue_tracker: https://github.com/nlfiedler/oxidized/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  equatable: ^1.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
